import "./globals.css";

import './App.css'
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "./Components/Navbar";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>

      <a href='/'><img src='https://cdn-icons-png.flaticon.com/512/1096/1096090.png' alt ='Logo' className="IMGlogo"></img></a>

{/*** Navbar ***/}

<Navbar/>

{/** Footer ***/}



<footer className="FooterSection"><h1>Contact me</h1>
<p className="Tel">My Tel : 50099026</p>
<p className="Mail">Mail: Messamessus@yahoo.com</p>
<p className="Local">Localisation : Manar I Rue Mohamed Abd El Wahab</p>
  </footer>

    </html>
  );
}
